# Generated by Django 4.2.6 on 2023-10-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling_unit',
            name='date_entered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polling_unit',
            name='entered_by_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='polling_unit',
            name='lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='polling_unit',
            name='lga_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polling_unit',
            name='long',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='polling_unit',
            name='polling_unit_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polling_unit',
            name='polling_unit_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polling_unit',
            name='polling_unit_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='polling_unit',
            name='polling_unit_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='polling_unit',
            name='uniqueid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polling_unit',
            name='uniquewardid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polling_unit',
            name='user_ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='polling_unit',
            name='ward_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
